- id: trivyfs-docker
  name: trivyfs-docker
  entry: aquasec/trivy:0.44.0 fs --exit-code 1
  language: docker_image
  pass_filenames: false

- id: trivyconfig-docker
  name: trivyconfig-docker
  entry: aquasec/trivy:0.44.0 config --exit-code 1
  language: docker_image
  pass_filenames: false